# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae79ef1e92112de8ab7375d0bd82778ab9161d4712f89794c2a7bf1d19a259a92d014373d86e78876718599307e40854676633376e8f67390ba9ef98a89d7d9

test:
  secret_key_base: c94788633e4dac2ce002f12102b3bbc2aeab3d5fe9f9da851fd5ec380296c6798c5434d5b7a5444cb8cce7016eee65cddb837e1b8b26b0d0445a990dc83829c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
